export const TOGGLE_FAVORITE_EAT = "TOGGLE_FAVORITE_EAT";
export const TOGGLE_FAVORITE_DOP = "TOGGLE_FAVORITE_DOP";
export const CHANGE_FAVORITE_EAT = "CHANGE_FAVORITE_EAT";
export const CHANGE_FAVORITE_DOP = "CHANGE_FAVORITE_DOP";
