export const TOGGLE_FAVORITE_BUFFETS = "TOGGLE_FAVORITE_BUFFETS";
export const TOGGLE_FAVORITE_GASTRO = "TOGGLE_FAVORITE_GASTRO";
export const TOGGLE_FAVORITE_MASTERCLASS = "TOGGLE_FAVORITE_MASTERCLASS";
export const TOGGLE_FAVORITE_BAR = "TOGGLE_FAVORITE_BAR";
export const TOGGLE_FAVORITE_DOP = "TOGGLE_FAVORITE_DOP";
